#!/bin/bash

# - Ensures the latest docker container is built
# - Runs the docker container, exporting the current directory into the
#   /opt/hubward dir in the container
# - Runs docker-test.sh inside the container

set -e
docker build -t daler/hubward-test .
docker run -it -v $(pwd):/opt/hubward daler/hubward-test /bin/bash docker-test.sh
